### ISSUE TITLE
Investigate Audio

### ISSUE THREAD

**Issue by Javrel** [Javrel/TBD#10]
**As a** dev team
**We want** to gain some info knowledge on audio in godot
**So that** we can prepare to get started

**ACs**
* we know what audio formats can be used in godot for music and sound effects
* A recomendation from our sound guy on format to use
* Any additional format capability we dont have thats required is identified

**Comment by ThisUsernameWasTaken** [comment]
1: Audio formats compatible with the latest stable build of Godot are .wav .ogg and .mp3

2: Long duration audio should be .mp3 unless it is a large degradation in the quality of the audio from compression.  Things like music tracks, long speeches or dialogue, narration etc. If the duration of the sound clip > 10 seconds consider MP3 to save space. The caveat to using MP3 files is that they require more processor power from the player to decode the files and can result in performance issues if over used.

3: Short duration audio such as sound effects that are repeatedly called upon during gameplay should be .wav or .ogg. They are less intensive on the CPU as they are lossless files but the caveat is that the file sizes are very large as a result.  Keeping these files reserved for short duration audio should reduce the bloat size of the final package and ease system requirements

4: The DAW that I use is capable of generating both MP3 and WAV files so there should not be any additional needs as far as this is concerned..
